services:
  - type: web
    name: portugal-realty
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: APP_PASSWORD
        sync: false
      - key: APP_ADMIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: NEON_DATABASE_URL
        sync: false
